# Name of your application. Used to uniquely configure containers.
service: boardgame_explorer

# Name of the container image.
image: nicollinoxx/boardgame_explorer

# Deploy to these servers.
servers:
  web:
    - 46.224.4.204

# Configure proxy with subdomain of fitplan.vip
# Access via: https://boardgame.fitplan.vip
proxy:
  ssl: true
  host: boardgame.fitplan.vip

# Credentials for your image host.
registry:
  username: nicollinoxx
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    # Solid Queue disabled - not using background jobs
    SOLID_QUEUE_IN_PUMA: false

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
volumes:
  - "boardgame_explorer_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
